library(sqldf)
path = "data.1.txt"
data <- read.csv.sql(path, sep=";",sql = 'select * from file where Date = "1/2/2007" or Date = "2/2/2007"')
data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(data$Date,data[,3],type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(data$Date,data[,7],type="l",col="black",ylab="Energy sub metering",xlab="")  
 lines(data$Date,data[,8],col="red")
 lines(data$Date,data[,9],col="blue")
 legend("topright",xjust=1,pch="_",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$Date,data$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(data$Date,data[,4],xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()
