library(sqldf)
path = "data.1.txt"
data <- read.csv.sql(path, sep=";",sql = 'select * from file where Date = "1/2/2007" or Date = "2/2/2007"')
data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
plot(data$Date,data[,7],type="l",col="black",ylab="Energy sub metering",xlab="")
lines(data$Date,data[,8],col="red")
lines(data$Date,data[,9],col="blue")
legend("topright",pch="___",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()